name: dgame
version: 0.1.0
author: Eric J. Smith <eric@codesmithtools.com>
description: A Dart game engine library.
homepage: https://github.com/ejsmith/dgame
dependencies:
  unittest: any

#dependencies:
#  js: any
#  unittest: any