name: dgame
version: 0.1.1
author: Eric J. Smith <eric@codesmithtools.com>
description: A game engine library for Dart.
homepage: https://github.com/ejsmith/dgame
dependencies:
  unittest: any

#dependencies:
#  js: any
#  unittest: any