name: dgame
version: 0.3.1
author: Eric J. Smith <eric@codesmithtools.com>
description: A game engine library for Dart.
homepage: https://github.com/ejsmith/dgame
dependencies:
  event_stream: any
  unittest: any
